changesDir: changes
unreleasedDir: unreleased
headerPath: header.tpl.md
changelogPath: CHANGELOG.md
versionExt: md
versionFormat: '## {{.Version}} - {{.Time.Format "2006-01-02"}}'
kindFormat: '### {{.Kind}}'
changeFormat: '* [#{{.Custom.PR}}](https://github.com/YafimK/testgoreleaser/pull/{{.Custom.PR}}) {{.Body}}'
kinds:
  - label: Added
  - label: Changed
  - label: Deprecated
  - label: Removed
  - label: Fixed
  - label: Security
custom:
- key: PR
  type: int
  minInt: 1